server:
  port: 5052

spring:
  application:
    name: TASK-SERVICE

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/task_service
    username: root
    password: anshmkk
    driver-class-name: com.mysql.cj.jdbc.Driver